# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ADMIN\Desktop\ServerApplicationAsOn10-7\ServerApplication\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbClose = QtWidgets.QPushButton(self.centralwidget)
        self.pbClose.setGeometry(QtCore.QRect(530, 350, 89, 25))
        self.pbClose.setObjectName("pbClose")
        self.pbSendMessage = QtWidgets.QPushButton(self.centralwidget)
        self.pbSendMessage.setGeometry(QtCore.QRect(430, 290, 121, 25))
        self.pbSendMessage.setObjectName("pbSendMessage")
        self.pbDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pbDisconnect.setGeometry(QtCore.QRect(610, 150, 111, 25))
        self.pbDisconnect.setObjectName("pbDisconnect")
        self.teMessageHistory = QtWidgets.QTextEdit(self.centralwidget)
        self.teMessageHistory.setGeometry(QtCore.QRect(20, 60, 431, 151))
        self.teMessageHistory.setObjectName("teMessageHistory")
        self.lbServer = QtWidgets.QLabel(self.centralwidget)
        self.lbServer.setGeometry(QtCore.QRect(20, 30, 141, 17))
        self.lbServer.setObjectName("lbServer")
        self.leTextMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.leTextMessage.setGeometry(QtCore.QRect(20, 290, 401, 21))
        self.leTextMessage.setObjectName("leTextMessage")
        self.lbShow = QtWidgets.QLabel(self.centralwidget)
        self.lbShow.setGeometry(QtCore.QRect(20, 260, 161, 20))
        self.lbShow.setObjectName("lbShow")
        self.pbClearText = QtWidgets.QPushButton(self.centralwidget)
        self.pbClearText.setGeometry(QtCore.QRect(322, 220, 131, 29))
        self.pbClearText.setObjectName("pbClearText")
        self.leHostIPAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.leHostIPAddress.setGeometry(QtCore.QRect(610, 60, 113, 25))
        self.leHostIPAddress.setObjectName("leHostIPAddress")
        self.leHostPort = QtWidgets.QLineEdit(self.centralwidget)
        self.leHostPort.setGeometry(QtCore.QRect(610, 100, 113, 25))
        self.leHostPort.setObjectName("leHostPort")
        self.lbServerIP = QtWidgets.QLabel(self.centralwidget)
        self.lbServerIP.setGeometry(QtCore.QRect(470, 60, 131, 17))
        self.lbServerIP.setObjectName("lbServerIP")
        self.lbServerPort = QtWidgets.QLabel(self.centralwidget)
        self.lbServerPort.setGeometry(QtCore.QRect(470, 100, 131, 17))
        self.lbServerPort.setObjectName("lbServerPort")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server-Side Application"))
        self.pbClose.setText(_translate("MainWindow", "&Close"))
        self.pbSendMessage.setText(_translate("MainWindow", "Send Messages"))
        self.pbDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.lbServer.setText(_translate("MainWindow", "Message History"))
        self.leTextMessage.setText(_translate("MainWindow", "Hello2"))
        self.lbShow.setText(_translate("MainWindow", "Message"))
        self.pbClearText.setText(_translate("MainWindow", "Clear Messages"))
        self.leHostIPAddress.setText(_translate("MainWindow", "127.0.0.1"))
        self.leHostPort.setText(_translate("MainWindow", "8000"))
        self.lbServerIP.setText(_translate("MainWindow", "Server IP Address"))
        self.lbServerPort.setText(_translate("MainWindow", "Server Port"))
